### ISSUE TITLE
no choice backstabbing

### ISSUE THREAD

**Issue by gruzin007** [BGforgeNet/bg2-wildmage#7] opened 2017-11-07 15:03 UTC
When choice feats no select a special ability Backstabbing. Wild mage it has 18 DEX.

**Comment by burner1024** [comment] 2017-11-07 16:53
Can't reproduce. More details, weidu.log?

**Comment by burner1024** [comment] 2018-06-17 11:52
Closing as can't reproduce.

**Closed as completed by burner1024** 2018-06-17 11:52 UTC
