### ISSUE TITLE
wm_cow spell kill all bug/feature

### ISSUE THREAD

**Issue by OverDrone** [BGforgeNet/bg2-wildmage#8] opened 2018-04-14 23:46 UTC
Hello!
I've experience strange wm_cow spell behaviour:
If you target party member or hostile creature which moved after you targeted it, this spell is applied to ALL creatures on the map including all party members. 
If you target hostile creature that was holding still (i.e. attacking your party meelee) everything works as expected - all effects are applied to that single poor creature.

Yes, you may say it's a wild magic, but I doubt it was coded this way.

I play bws build. I'm attaching weidu and spell just in case.
Also just in case... I don't have any problems with other wm_ spells I obtained by now. They work according to description. I even modified AdvancedAI to include selected wm_ spells there.
[archive.zip](https://github.com/BGforgeNet/bg2-wildmage/files/1911461/archive.zip)

**Comment by burner1024** [comment] 2018-04-15 09:27
Ahahaha. "It's raining cows, hallelujah...". Must look epic. I'll actually consider adding a surge like that.

I will look into this in due time, which I can't promise to be soon, but before the next release.

**Comment by burner1024** [comment] 2018-04-24 04:51
Also, could you run `weidu --change-log wm_cow.spl` and post the output?

**Comment by OverDrone** [comment] 2018-04-24 22:26
Mods affecting WM_COW.SPL:
00000: ~ATWEAKS/SETUP-ATWEAKS.TP2~ 0 160 // PnP Undead: v4.52 BWP Fix
00001: ~IISPELLSYSTEMADJUSTMENTS/SETUP-IISPELLSYSTEMADJUSTMENTS.TP2~ 0 0 // Arcane Spell Refreshment: v7.1

first I dunno what is doing. second adds one effect: spell refreshment. I'ts working fine, I didn't notice any problems with other spells. I can also try install wildmage mod on clean bg2ee and see if it still reproduces...

**Comment by burner1024** [comment] 2018-04-25 05:46
Thank you.
You can try reproducing on clean installation if you want, but it's not necessary.

**Comment by burner1024** [comment] 2018-06-14 15:01
You know what, I've been going through original readme, and here's what I found:
> "Summon Cow" occasionally damages every creature in the whole area.
>    this seems to be hard-coded and intended by Bioware. It also happens
>    with the wild surge and the original 2nd level "Easter Egg"-spell

Can you reproduce this reliably with a moving target? Or was is a one-off chance?
If it was, I'd probably be inclined to leave it as it is, maybe only adding a note to description.

**Comment by OverDrone** [comment] 2018-06-15 00:38
It was reproducible for me for every time I moved target out of the way. There is nothing wrong if all on level are damaged. Let's call it a feature. But the problem is that my party loose some equipped gear and it's very tedious to collect it back then remember who was the owner of which item.
I can't reproduce it right now because I stopped playing BG for some time, I can check it next time I return to BG

**Comment by burner1024** [comment] 2018-06-15 08:08
I've tried with a party member, hostile, your file as well - on BGT classic. Can't reproduce. Might be EE-specific, but I don't have EE installed at the moment. You have a Classic version?

**Comment by burner1024** [comment] 2018-06-17 12:07
Closing as can't reproduce for now. A note is added to readme.

**Closed as completed by burner1024** 2018-06-17 12:07 UTC

**Comment by OverDrone** [comment] 2018-07-02 23:52
I don't have BGT classic installed right now. I'll try to reproduce it when/if I install it. I hope you'll get your copy of BGEE. It was recently with big discount on steam, all 3 parts...

**Comment by burner1024** [comment] 2018-07-04 04:59
I have them purchased, just need to download and install...
